import streamlit as st
import sys
import os

# Ensure the `common` directory is in the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'common')))

from gemini_utils import get_gemini_response, convert_rows_to_sentences
from db_utils import read_sql_query

table = """         
           table = CHATGPT_BOOKING_FORM, fields= (NUMBER: 422, BOOKING_FORM_STATUS: Booking Form Not Attached / Booking Form Attached),
           table = CHATGPT_BROKER_MASTER, fields= (BROKER_REGISTED_DATE: 24-JUN-22,	BROKER_ID: 188, CREATED_ON: 6/24/2022 9:58,	BROKER_NAME: Milestone Home Real Estate Brokers, TELEPHONE: 9714 4516355, EMAIL: makhan@mshre.ae, MOBILE: 971585765338, AGENT: 1, ORG_NAME: FAKHRUDDIN PROPERTIES DEVELOPMENT LIMITED, IS_ACTIVE: 0/1, IS_CONFIRMED_BY: 5236, IS_VERIFIED_BY: 5250);
           table = CHATGPT_CUSTOMER_BAL, fields= (CUSTOMER_ID: 422, CUSTOMER_NAME: Vivek Jadon, UNITID:	892, UNIT_CODE: MGT1-FL22-2203, SALE_VALUE: 1,000,000.00, OFFER_NO: 791, CINVOICENO: RES-422, RESERVE_NO: 431, DOC_DATE: 16-Aug-22, DOC_TYPE: ERES / INSTALLMENT, INV_AMT: 20,000.00, INV_BALANCE: (invoice amount - paid = invoice balance) 19,500.00, UNASSIGNED: 1,000, RESERVE_DATE: 16-Aug-22, BOOKING_DATE: 9-Nov-22, OUTSTANDING_DAYS: 5, PDC: 1,000.00);
           table = CHATGPT_CUSTOMER_CONTACT, fields= (CUSTOMER_CREATED_ON: 23-Feb-2023, CUSTOMER_ID: 422, CTYPE: Person / Org, CUSTOMER_NAME: Vivek Jadon, FIRST_NAME: Vivek, LAST_NAME: Jadon, CONTACT_TYPE_NAME: EMAIL / MOBILE, VALUE: info@gmail.com / +971556003992, IS_DISABLED: 0 / 1, IS_PRIMARY: 0 / 1);
           table = CHATGPT_CUSTOMER_MASTER, fields= (CUSTOMER_ID: 422, CTYPE: Person, CUSTOMER_NAME: Vivek Jadon, FIRST_NAME: Vivek , LAST_NAME: Jadon, PASSPORT_NO: Z123456789, PASSPORT_EXPIRY_DATE: 23-FEB-2028, VISA_EXPIRY_DATE: 23-FEB-2024, DOB:	23-Feb-1984, COUNTRY_ID: 52, NATIONALITY);
           table = CHATGPT_PRA, fields= (ID, OFFER_NO, CUSTOMER_NAME, RESERVE_DATE, CLIENT_SIGN_DATE, MGMT_SIGN_DATE, CLIENT_HANDOVER_DATE, PRA_STATUS, UNIT_STATUS, AGENT_ID, ORG_ID, UNIT_CODE, STATUSDT, USER_INFO_ID, CREATED_BY);
           table = CHATGPT_UNIT_MASTER, fields= (BUILDING: TOWER A / TOWER B, UNIT_CODE: MGT2-FL23-2301, UNIT_NUMBER: 2301, GROSS_AREA: 1000.56, BALCONY_AREA: 52.36, SALE_VALUE: 2,000,000.00, UNIT_SPECS_NAME: 1 BHK / STUDIO / 2 BHK, UNIT_TYPE_NAME: TYPE 1 / TYPE A, UNIT_VIEW_NAME: Barsha South View, UNIT_OPEN_FOR_SALE: Yes / No, UNIT_STATUS: Booked / Reservation cancellation in progress / Available / Reserved);
           table = CHATGPT_SALE_MASTER, fields= (BUILDING: TOWER A / TOWER B, UNIT_CODE: MGT1-FL22-2201, UNIT_NUMBER: 2313, GROSS_AREA: 3242.34, BALCONY_AREA: 42.5, SALE_VALUE: 525000, OFFER_NO: 430, BLOCK_DATE: 15-Aug-22, RESERVE_NO: 92, BOOKING_DATE: 22-Aug-22, BOOKING_NO: 117, UNIT_STATUS: Booked, AGENT_NAME: Vandana, BROKER_NAME: PHIRDOS STAR PROPERTY, CUSTOMER_NAME: Arthur Colibao, CUSTOMER_ID: 434, NATIONALITY, INV_BALANCE: 19,500.00);
           table = CHATGPT_RECEIPT_DTL, fields= (RECEIPT_NO: 767, RECEIPT_DATE: 12-Mar-2022, CUSTOMER_ID: 324, NARRATION: AED 8,433.63/- Payment Received Towards Installment For Unit 2506., RECEIVED_FROM: Taj, OFFER_NO: 233, SEC_DEPO_RECEIPT: No / Yes, MODE_OF_PAY: CASH / CREDIT CARD / BY LINK / CHEQUE / BANK TRANSFER, unit_id: 4343,CHEQUE_NO: 012354, CHEQUE_DATE: 12-Mar-2022,UNIT_CODE: MGT1-FL19-1902, BUILDING: TOWER A);
           table = CHATGPT_RECEIPT_DTL2, fields= (RECEIPT_NO: 767, RECEIPT_DATE: 12-Mar-2022, CUSTOMER_ID: 324, NARRATION: AED 8,433.63/- Payment Received Towards Installment For Unit 2506., RECEIVED_FROM: Taj, OFFER_NO: 233, SEC_DEPO_RECEIPT: No / Yes, MODE_OF_PAY: CASH / CREDIT CARD / BY LINK / CHEQUE / BANK TRANSFER, unit_id: 4343,CHEQUE_NO: 012354, CHEQUE_DATE: 12-Mar-2022,UNIT_CODE: MGT1-FL19-1902, BUILDING: TOWER A, customer:'Vishal anand');
           table = CHATGPT_NOTES, fields= (NOTE: Payment Plan Invoice Email has Sent, OFFER_NO: 123, CREATED_ON: 12-Mar-2022, LOGIN_NAME: Seeniya);
           table = CHATGPT_PAYMENT_PLAN, fields= (OFFER_NO: 422, INSTALLMENT: 1, DUE_DATE: 12-Mar-2022, PERCENTAGE: 20, DESCRIPTION: 2nd installment, AMOUNT: 1,000,000.00, INVOICE_NO: RES-464-1, INVOICE_FLAG: Invoice not raised / Invoice Raised);
           table = VW_LEAD, fields=(ID, NAME, STATUS, SOURCE, LEAD_SOURCE, ZOHO_USER_EMAIL, LEAD_TYPE_ID, CREATED_ON, TAG)
           table = CHATGPT_HM_PACKAGE_HDR, fields=(HDR_ID, ORG_ID, PROPERTY_ID, LOCATION_ID, ORG_NAME, BUILDING, LOCATION_NAME, IS_CONFIRM, IS_ACTIVE, PACKAGE_NAME)
           table = CHATGPT_HM_PACKAGE_DTL, fields=(DTL_ID, HDR_ID, AMENTIES_TYPE_ID, AMENITIES_TYPE, QTY, PRICE, DESCRIPTION)
           table = FND_COUNTRY, fields = (COUNTRY_ID,COUNTRY_NAME,COUNTRY_TEL_CODE,COUNTRY_CODE,NATIONALITY)
           table = FND_USER_INFO, fields = (USER_INFO_ID,EMPLOYEE_ID,COUNTRY_ID,CITY_ID,ADDRESS,FIRST_NAME,LAST_NAME,GENDER,DOB,DOJ,DEPARTMENT_ID,DESIGNATION_ID,MOBILE,EMAIL,LOGIN_NAME,IS_ACTIVE,IS_DELETED,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,USER_LEVEL,CUSTOMER_STATUS,IS_LOGGED_IN,IS_MOBILE_LOGIN,ROI_EMAIL,CUSTOMERID,LEGAL_ENTITY_ID,MODERATOR,IS_LOCKED,LOGIN_ATTEMPT)
           table = PN_RESERVATION_HDR, fields = (ID, PRE_RESERVE_NO, PRE_RESERVE_DATE, RESERVE_NO, RESERVE_DATE, BOOKING_NO, BOOKING_DATE, PROPERTY_ID, UNIT_ID, UNIT_DESC_ID, GROSS_AREA, SALE_VALUE, PRICE, PAYMENT_PLAN_ID, AGENT_ID, BROKER_ID, SOURCE, STATUS, ZOHO_REF_ID, IS_ACTIVE, IS_DELETED, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, ORG_ID, LEAD_ID, DEAL_ID, HOME_AUTO_HDRID, IS_WELCOME_EMAIL_SENT, IS_OVER_DUE_EMAIL_SENT, IS_ERES_EMAIL_SENT, IS_CC_EMAIL, IS_CANCEL_EMAIL, IS_AGENT_EMAIL1, IS_AGENT_EMAIL2, IS_AGENT_EMAIL3, IS_AGENT_EMAIL4, IS_AGENT_EMAIL5, IS_AGENT_EMAIL6, IS_AGENT_EMAIL7, IS_AGENT_EMAIL8, IS_AGENT_EMAIL9, IS_CO_EMAIL_SENT, OLD_AGENT_ID, IS_FINAL_EMAIL, ESCROW_EMAIL, TWO_DAYS_NOTICE, FOURTYEIGHT_HRS_NOTICE, CSD_CALL_TO_CUST, TWO_DAYS_SENT_TIME, FOURTYEIGHT_HRS_SENT_TIME, CUS_EMAIL, CUS_EMAILS, SPA_ADDRESS_EMAIL, DEAL_CREATED, TAG_ID, PDR, ODR, CDR, UNIT_ALLOCATION)
           table = PN_RESERVE_CUSTOMER_DTL, fields = (ID, RESERVATION_ID, CUSTOMER_ID, PERCENTAGE, IS_PRIMARY, IS_ACTIVE, IS_DELETED, IS_CONFIRM, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, ORG_ID)
           table = AR_CUSTOMER, fields = (CUSTOMER_ID, CTYPE, NAME, FIRST_NAME, LAST_NAME, EID, VAT_TRN_NO, CONTACT_PERSON, PASSPORT_NO, PASSPORT_EXPIRY_DATE, VISA_EXPIRY_DATE, DOB, NATIONALITY, ZOHO_CUSTOMER_ID, OLD_CUSTOMER_ID, IS_ACTIVE, IS_DELETED, IS_CONFIRM, COUNTRY_ID, CITY_ID, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, PASS_COPY_PATH, PASS_COPY_NAME, VISA_COPY_PATH, VISA_COPY_NAME, EID_COPY_PATH, EID_COPY_NAME, PO_BOX, ADDRESS, BDAY_FLAG, TEMPLATE_ID, AUTO_REMINDER, RES_COUNTRY, RES_CITY, RES_ADDRESS, IS_CC_EMAIL, NAME_ARBI, BLOG_EMAIL, UNSUBSCRIBE_BLOG, TEMP_EMAIL, PP_DATE, FLAG_DND, BRANDED, GENDER, PR_AUTO_EMAIL, OR_AUTO_EMAIL, BANK_ACC_MG, BANK_ACC_HATIMI)
           table = PN_SALES_STATUS, fields = (STATUS_ID,STATUS)
           table = PN_UNITS, fields = (UNIT_ID, UNIT_CODE, NET_AREA, GROSS_AREA, SALEABLE_AREA, BALCONY_AREA, PROPERTY_ID, UNIT_TYPE_ID, UNIT_SPECS_ID, UNIT_VIEW_ID, IS_CONFIRM, IS_ACTIVE, IS_DELETED, ATTRIBUTE5, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, NDOC, ORG_ID, OFFICE_SECTION_TYPE, COMMON_AREA, FLOOR_ID, UNIT_NUMBER, UNIT_MEASURE, UNIT_SPEC_AREA, PRICE_TYPE, PRICE_VALUE, IS_RELEASED, PARK_SPACE, IS_COMMERCIAL, LAYOUT_URL, IS_SHARIYAH, PARKNO)
           table = PN_AGENTS, fields = (ID, ORG_ID, USER_ID, ZOHO_USER_EMAIL, IS_ACTIVE, IS_DELETED, IS_CONFIRM, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, IS_ASSIGNED, AUTO_ALLOCATION, SEQ, CURRENT_SEQ)
           table = CHATGPT_RELEASED_NOTRELEASED, fields = (UNIT_ID, UNIT_CODE, UNIT_NAME, PROPERTY_ID, UNIT_SPECS_ID, ORG_ID, FLOOR_ID, PRICE_TYPE, PRICE_VALUE, ORG_NAME, UNIT_SPECS_NAME, PROPERTY_CODE, FLOOR_CODE, GROSS_AREA, IS_RELEASED)
           table = CHATGPT_VISA, fields = (COUNTRY_NAME, UID_NO, PASSPORT_NO, PROFESSION, SPONSOR, ISSUE_DATE, EXPIRTY_DATE, REMARKS)
           table = CHATGPT_PASSPORT, fields = (PASSPORT_NUM, NAME, NATIONALITY, COUNTRY_NAME, GENDER, DOB, PLACE_OF_BIRTH, PLACE_OF_ISSUE, FATHER_NAME, CONTACT, EMAIL, REMARKS, MOTHER_NAME, SPOUSE_NAME, ADDRESS, OLD_PASSPORT_NO)
           table = CHATGPT_EID, fields = (EID, NAME, NATIONALITY, SEX, DOB, CARD_NUMBER, EXPIRTY_DATE, REMARKS)
           table = CHATGPT_TICKETS, fields = (REMARKS, TICKET_NO, EMAIL, STATUS, TYPE, CATEGORY, ASSIGNED_TO, IS_MUTE, CREATED_ON, FILE_COUNT, TOTAL_TIME, CUSTOMER, UNIT_CODE)
           table = CHATGPT_SPA, fields = (ID, OFFER_NO, CUSTOMER_NAME, RESERVE_DATE, CLIENT_SIGN_DATE, MGMT_SIGN_DATE, CLIENT_HANDOVER_DATE, SPA_STATUS, UNIT_STATUS, AGENT_ID, ORG_ID, UNIT_CODE, STATUSDT, USER_INFO_ID, CREATED_BY, DOWNLOAD_COUNT)
           table = CHATGPT_SOLD_UNSOLD, fields = (BUILDING, UNIT_CODE, UNIT_NUMBER, GROSS_AREA, SALE_VALUE, UNIT_SPECS_NAME, UNIT_STATUS, OFFER_NO, PRE_RESERVE_DATE, CUSTOMER_NAME, AGENT_NAME, BROKER_NAME, OLD_AGENT_ID, INV, DUE, PAID, PENALTY, PDC, REG_BAL, ERES_BAL, UNASSIGN)
           table = CHATGPT_OQOOD, fields = (PRE_RESERVE_NO, ORDER_ID, CUSTOMER_NAME, UNIT_CODE, POSTING_DATE, OQOOD_REG_NO, REGISTER_DATE, DESCRIPTION, AMOUNT, CREATED_ON, CREATED_BY)
           table = CHATGPT_LATEPAYMENT_FEE, fields = (CUSTOMER_NAME, UNITNAME, PRE_RESERVE_NO, CINVOICENO, INVOICE_DATE, LATEPAYMENT_NO, LATEPAYMENT_DATE, INVOICE_AMOUNT, INVOICE_BALANCE, PRE_RES_ID, APPROVAL_STATUS, APPROVER_USER_ID, RECEIVED_DATE, REMARKS, FINAL_APPROVAL)
           table = CHATGPT_PDC, fields = (RECEIPT_NO, RECEIPT_DATE, NARRATION, CHEQUE_NO, AMOUNT, DUE_DATE, MODE_OF_PAY, USER_NAME, ORG_NAME, CUSTOMER_NAME, UNIT_CODE, PRE_RESERVE_NO, IS_CHEQUE_CANCELLED, NATIONATIONALITY)
           table = CHATGPT_SALES_TITLEDEED, fields = (STATUS, PRE_RESERVE_NO, TITLE_DEED, REG_DATE, DESCRIPTION, UNIT_CODE, ORG, CUSTOMER_NAME)
           table = CHATGPT_SECURITY_DEPOSIT, fields = (TRACK_CODE, SEC_DEPO_REF, RECEIPT_NO, RECEIPT_DATE, CUSTOMER, EMAIL, NATIONALITY, CONFIRMED_BY, CONFIRMED_ON, PREPARED_BY, CNARRATION, REFERENCE_CODE, RECEIVED_FROM, PRE_RESERVATION, AMOUNT, PRE_RESERVATION_ID)
           table = CHATGPT_UNIT_CANCELLATION, fields = (PRE_RESERVATION_DATE, CUSTOMER_NAME, BOOKING_DATE, RESERVATION_DATE, PRE_RESERVE_NO, ORG_NAME, STATUS, LOCATION_NAME, APPROVAL_DATE, REASON, RESERVATION_ID, APPROVAL_FLAG, UNIT_TYPE, UNIT_CODE, BROKER_NAME)
           table = CHATGPT_UNIT_TRANSFER, fields = (PRE_RESERVATION_DATE, BOOKING_DATE, RESERVATION_DATE, APPROVED_DATE, REASON, TRANSFER_CUSTOMER, STATUS, UNIT_CODE, ORG_NAME, BROKER_NAME, CUSTOMER_NAME, LOCATION_NAME)
           table = CHATGPT_14PERCENT_BUCKET, fields = (PRE_RESERVE_NO, SALE_VALUE, AGEING, STATUS, UNIT_NAME, RESERVE_NO, FOURTYEIGHT_HRS_SENT_TIME, CUSTOMER_NAME, NATIONALITY, AGENT, BROKER, RESERVE_DATE, TWO_DAYS_SENT_TIME, TWO_DAYS_NOTICE, FOURTYEIGHT_HRS_NOTICE, CSD_CALL_TO_CUSTOMER, INVOICE_AMT, INVOICE_BALANCE, PDC, REG, ERES, TOTAL, HOLD, HOLD_DATE)
           table = CHATGPT_INSTALLMENT_BUCK, fields = (PRE_RESERVE_NO, STATUS, AGENT, SALE_VALUE, DESCRIPTION, INVOICE_NO, PERCENTAGE, UNIT_CODE, CUSTOMER_NAME, REMINDER13, REMINDER17, COR_NOTICE, LANDDEPT_NOTICE, NEWSPAPER_ADS, SUBMIT_LAND_DEPT, BALANCE, AMOUNT, DUE_DATE, GROUP_AGING, ORG)
           table = CHATGPT_INSTALLMENT_BUCK_2DUE, fields = (PRE_RESERVE_NO, STATUS, AGENT, SALE_VALUE, DESCRIPTION, INVOICE_NO, PERCENTAGE, UNIT_CODE, CUSTOMER_NAME, REMINDER, REM17, COR_NOTICE, LAND_DEPT_NOTICE, NEWSPAPER_ADS, SUBMIT_LAND_DEPT, BALANCE, AMOUNT, DUE_DATE, GROUP_AGING, ORG)
           table = CHATGPT_BUILDING_MASTER, fields = (OWNER_OF_TITLE, MASTER_DEVELOPER, PURCHASE_PRICE, PREMIUM_BROKERAGE, REGISTRATION_FEES, PURCHASE_RATE, COST_OF_CONSTRUCTION, BUIDLING_LAND_TYPE, PROPERTY_CODE, PROPERTY_NAME, PURCHASE_DATE, PURCHASE_AMOUNT, CONTRACTOR, CONSULTANT, FOLDER_NO, PLOTNO, BUA, AREAMETER, AREAFEET, ADDRESS, PURCHASEPRICE, REMARKS, COMM, OWNER, PP_OWNER, CURRENCY, UNIT_TYPE, MAX_ID, LOCATION_CODE, COUNTRY_NAME, CITY_NAME, ORG_NAME, PROPERTY_TYPE_NAME, LOCATION)
           table = CHATGPT_APPROVAL_PATH, fields = (APPROVAL_LEVEL, LEVEL_NAME, USER_NAME, APPROVAL_PATH_NAME, LEGAL_ENTITY)
           table = CHATGPT_OTHER_CHARGES, fields = (BUILDING, CALCULATION_TYPE, BROKER_COMMISSION, NAME, AMOUNT, PERCENTAGE, CATEGORY, OTHER_CHARGE_NAME, ORG, STATUS)
           table = CHATGPT_FLOOR_MASTER, fields = (BUILDING, ORG_NAME, FLOOR_CODE, FLOOR_NAME, NET_AREA, GROSS_AREA)
           table = CHATGPT_UNIT_VIEW_MASTER, fields = (UNIT_VIEW_NAME, ORG_NAME, LOCATION_CODE, BUILDING)
           table = CHATGPT_UNIT_DESC_MASTER, fields = (DESCRIPTION, PENALTY_AMT, BUILDING, ORG_NAME, LOCATION)
           table = chatgpt_pre_reserved, fields = (BUILDING, UNIT_CODE, UNIT_NUMBER, GROSS_AREA, BALCONY_AREA, SALE_VALUE, OFFER_NO, BLOCK_DATE, RESERVE_NO, BOOKING_DATE, BOOKING_NO, UNIT_STATUS, AGENT_NAME, BROKER_NAME, CUSTOMER_NAME, CUSTOMER_ID, UNIT_SPECS_NAME, NATIONALITY, INV_BALANCE, OQOOD_REGISTRATION_STATUS, OQOOD_REG_NO, REG_DATE, ORDER_ID)
           table = CHATGPT_RESERVATION_MASTER, fields = (BUILDING, DEAL_CREATED, TAG_NAME, PRE_RESERVE_DATE, SALE_VALUE, BOOKING_DATE, RESERVE_DATE, PRE_RESERVE_NO, STATUS, UNIT, UNIT_TYPE, GROSS_AREA, PRICE_TYPE, PRICE_VALUE, ORG_NAME, BROKER_NAME, AGENT_NAME, CUSTOMER_NAME, NATIONALITY, DOB, COUNTRY,TOTAL_DUE,TOTAL_RECEIVED)
           table = CHATGPT_AVAILABLE_UNITS, fields = (UNIT, PRICE_VALUE, PRICE_TYPE, ORG_NAME, GROSS_AREA, PROPERTY_NAME, STATUS, UNIT_TYPE_NAME, UNIT_VIEW_NAME, UNIT_SPECS_NAME)
           """
## Define Your Prompt
prompt=[
    f"""
    Oracle 11gR2 SQL tables, with fields and examples(if applicable). Generate SQL query if you're not confident about tables or fields stated in prompt simply return your suggestion instead of query.
    
    Use this Tables and fields Only- {table}
    
    Please ensure the response is a valid PL/SQL block without a trailing semicolon at the end of each statement.
    Whenever the question includes the words "user" or "username", it refers to the column LOGIN_NAME in the table FND_USER_INFO.
    Whenever the question includes the words "customer", it refers to the column NAME in the table AR_CUSTOMER.
    
    Keep table aliases without the `AS` keyword.

    Amount or Money columns always mention as AED (dubai currency). 

    Convert date or timestamp columns as `DD-MON-YY` using the `TO_CHAR` function.

    For example,
    Example 1 - How many entries of records are present?, 
    the ORACLE SQL command will be something like this SELECT COUNT(*) FROM FND_USER_INFO

    Example 2 - Join format
    SELECT e.employee_id, e.first_name, e.last_name, d.department_name
    FROM employees e
    LEFT OUTER JOIN departments d ON e.department_id = d.department_id;

    Example 83 - Available units?
    SQL query: select UNIT,PRICE_VALUE,PRICE_TYPE,ORG_NAME,GROSS_AREA,PROPERTY_NAME as building,UNIT_VIEW_NAME AS UNIT_VIEW,UNIT_SPECS_NAME from CHATGPT_AVAILABLE_UNITS 

    Example 84 - Available units in Org hatimi
    SQL query: select UNIT,PRICE_VALUE,PRICE_TYPE,ORG_NAME,GROSS_AREA,PROPERTY_NAME as building,UNIT_VIEW_NAME AS UNIT_VIEW,UNIT_SPECS_NAME from CHATGPT_AVAILABLE_UNITS where upper(org_name) = upper('HATIMI') 
    
    Example 85 - Available units in Property or building 'HATIMI RESIDENCES TOWER A' ?
    SQL query: select UNIT,PRICE_VALUE,PRICE_TYPE,ORG_NAME,GROSS_AREA,PROPERTY_NAME as building,UNIT_VIEW_NAME AS UNIT_VIEW,UNIT_SPECS_NAME from CHATGPT_AVAILABLE_UNITS where upper(PROPERTY_NAME) = upper('HATIMI RESIDENCES TOWER A') 
    
    Example 86 - Pre reserved units today ?
    SQL query: select BUILDING,PRE_RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where TRUNC(PRE_RESERVE_DATE) = TO_DATE(SYSDATE, 'DD-MM-YY') and STATUS = 'Pre-Reserved'
    
    Example 87 - units booked by Germans 
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') AND upper(nationality) = upper('German')

    Example 88 - 2 bed room units booked/sold 
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') AND UNIT_SPECS_NAME = '2 BHK'

    Example 89 - pra status for unit MGT2-FL14-1405
    SQL query: select pra_status from CHATGPT_RESERVATION_MASTER where unit = 'MGT2-FL14-1405' 

    Example 90 - customers who is paid after due date crossed
    SQL query: SELECT a.RECEIPT_NO, a.RECEIPT_DATE, a.cheque_no, a.cheque_date, a.NARRATION, a.RECEIVED_FROM,a.sec_depo_receipt, a.mode_of_pay, a.unit_code, cus.name as customer FROM chatgpt_receipt_dtl2 a,ar_customer cus WHERE a.RECEIPT_DATE > a.cheque_date and cus.CUSTOMER_ID = a.CUSTOMER_ID group by a.RECEIPT_NO, a.RECEIPT_DATE, a.cheque_no, a.cheque_date, a.NARRATION, a.RECEIVED_FROM,a.sec_depo_receipt, a.mode_of_pay, a.unit_code, cus.name
    
    Example 91 - total collected amount by cash mode in last 1 month
    SQL query: SELECT SUM(AMOUNT) FROM chatgpt_receipt_dtl2 WHERE TRUNC(receipt_date) = TRUNC(SYSDATE) AND mode_of_pay = 'CASH' and RECEIPT_DATE BETWEEN SYSDATE - 30 AND SYSDATE

    Example 92 - year 2024 born cutomer passports
    SQL query: SELECT * from CHATGPT_PASSPORT where EXTRACT(YEAR FROM DOB) = 2024

    Example 93 - Indian customers who having passports
    SQL query: SELECT * FROM CHATGPT_PASSPORT WHERE lower(nationality) = lower('INDIAN')

    Example 94 - customers who having passport issued in Dubai
    SQL qeury: SELECT * FROM CHATGPT_PASSPORT WHERE lower(PLACE_OF_ISSUE) = lower('Dubai')

    Example 95 - visa's which is expired in 3 months
    SQL qeury: SELECT * FROM CHATGPT_VISA WHERE EXPIRTY_DATE BETWEEN SYSDATE AND ADD_MONTHS(SYSDATE, 3)

    Example 96 - india visa's
    SQL qeury: SELECT * FROM CHATGPT_VISA WHERE lower(COUNTRY_NAME) = lower('India')

    Example 96 - visa sponsored by Fakhruddin Properties
    SQL qeury: SELECT * FROM CHATGPT_VISA WHERE lower(SPONSOR) = lower('Fakhruddin Properties')

    Example 97 - assigned leads?
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE lower(STATUS) = lower('assigned')

    Example 98 - lead received from Email?
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE lower(SOURCE) = lower('Email')
    
    Example 99 - list the leads which has the type junk
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE lower(LEAD_TYPE) = lower('junk')

    Example 100 - Broker Company type leads
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE lower(LEAD_TYPE) = lower('junk')

    Example 101 - lead received by customer Shoaibkhan
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE lower(NAME) = lower('Shoaibkhan')

    Example 102 - last 1 month leads
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE CREATED_ON BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))
    
    Example 103 - lead received/created by last 1month
    SQL query: SELECT NAME as CUSTOMER,STATUS,SOURCE,ZOHO_USER_EMAIL,TAG AS LEADTYPE FROM VW_LEAD WHERE CREATED_ON BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))

    Example 104 - how many deals is created
    SQL query:  select led.NAME as CUSTOMER,led.STATUS,led.SOURCE,led.ZOHO_USER_EMAIL,led.TAG AS LEADTYPE from vw_lead led,pn_lead ledp where led.id = ledp.id and led.ID not in (SELECT lead_id from PN_RESERVATION_HDR where is_active=1 and is_deleted=0 and lead_id is not null) AND ledp.IS_DELETED = 0 AND ledp.LEAD_STATUS=7 ORDER BY led.ID desc

    Example 105 - deals created today
    SQL query:  select led.NAME as CUSTOMER,led.STATUS,led.SOURCE,led.ZOHO_USER_EMAIL,led.TAG AS LEADTYPE from vw_lead led,pn_lead ledp where led.id = ledp.id and led.ID not in (SELECT lead_id from PN_RESERVATION_HDR where is_active=1 and is_deleted=0 and lead_id is not null) AND ledp.IS_DELETED = 0 AND ledp.LEAD_STATUS=7 AND TRUNC(ledp.CREATED_ON) = TO_DATE(SYSDATE, 'DD-MM-YY') ORDER BY led.ID desc

    Example 106 - Deal created by customer SONWABILE BONGELA
    SQL query: select led.NAME as CUSTOMER,led.STATUS,led.SOURCE,led.ZOHO_USER_EMAIL,led.TAG AS LEADTYPE from vw_lead led,pn_lead ledp where led.id = ledp.id and led.ID not in (SELECT lead_id from PN_RESERVATION_HDR where is_active=1 and is_deleted=0 and lead_id is not null) AND ledp.IS_DELETED = 0 AND ledp.LEAD_STATUS=7 AND lower(led.NAME)=lower('SONWABILE BONGELA')  ORDER BY led.ID desc
    
    Example 107 - Deals created by walkin
    SQL query: select led.NAME as CUSTOMER,led.STATUS,led.SOURCE,led.ZOHO_USER_EMAIL,led.TAG AS LEADTYPE from vw_lead led,pn_lead ledp where led.id = ledp.id and led.ID not in (SELECT lead_id from PN_RESERVATION_HDR where is_active=1 and is_deleted=0 and lead_id is not null) AND ledp.IS_DELETED = 0 AND ledp.LEAD_STATUS=7 AND lower(led.SOURCE)=lower('Walk-In') ORDER BY led.ID desc

    Example 108 - Defaulter units or Defaulters
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE from CHATGPT_RESERVATION_MASTER mstr where mstr.STATUS_ID = 21 
    
    Example 109 - Pre reserved deafaulter units today ?
    SQL query: select BUILDING,PRE_RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where TRUNC(PRE_RESERVE_DATE) = TO_DATE(SYSDATE, 'DD-MM-YY') and STATUS = 'Pre-Reserved' and STATUS_ID = 21
    
    Example 110 - deafaulter units reserved by Germans 
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Reserved') AND upper(nationality) = upper('German') and STATUS_ID = 21

    Example 111 - 2 bed room defaulter units reserved
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Reserved') AND UNIT_SPECS_NAME = '2 BHK' and STATUS_ID = 21

    Example 112 - pra status for defaulter unit MGT2-FL14-1405
    SQL query: select pra_status from CHATGPT_RESERVATION_MASTER where unit = 'MGT2-FL14-1405' and STATUS_ID = 21

     Example 113 - Last month's total sale value for defaulter
    SQL query: SELECT SUM(Sale_value) last_month_salevalue FROM CHATGPT_RESERVATION_MASTER WHERE status IN ('Reserved') AND booking_date BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1)) and STATUS_ID = 21

    Example 114 - total received amount for defaulter unit MGR-GL-9
    SQL qeury: select mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE from CHATGPT_RESERVATION_MASTER mstr where mstr.STATUS_ID = 21 and unit = 'MGR-GL-9'
    
    Example 115 - units which have more than due 500 
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE from CHATGPT_RESERVATION_MASTER mstr where TOTAL_DUE > 500

    Example 116 - units of indians have more than 1500 due amount
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE from CHATGPT_RESERVATION_MASTER mstr where upper(nationality) = upper('Indian') AND total_due > 1500

    Example 117 - total due amount of booked units
    SQL query: select SUM(TOTAL_DUE) TOTAL_DUE from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') 

    Example 118 - total received amount of booked units
    SQL query: select SUM(TOTAL_RECEIVED) TOTAL_DUE from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') 

    Example 119 - units which has Due amount?
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE from CHATGPT_RESERVATION_MASTER mstr where TOTAL_DUE > 0

    Example 120 - units under Reservation cancel
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE,mstr.STATUS from CHATGPT_RESERVATION_MASTER mstr where STATUS = 'Reservation cancellation in progress'
    
    Example 121 - units under booking cancel
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE,mstr.STATUS from CHATGPT_RESERVATION_MASTER mstr where STATUS = 'Booking Cancellation in progress'
    
    Example 122 - units under pre reservation cancel
    SQL query: select mstr.PRE_RESERVE_NO,mstr.PRE_RESERVE_DATE,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.TOTAL_RECEIVED,mstr.TOTAL_DUE,mstr.STATUS from CHATGPT_RESERVATION_MASTER mstr where STATUS = 'Pre Reservation cancellation in progress'

    Example 123 - units booked by russian customers?
    SQL query: SELECT BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME,nationality FROM CHATGPT_RESERVATION_MASTER where lower(NATIONALITY) = lower('Russian') and status IN ('Booked','Reserved') 

    Example 124 - which customer booked most units this year
    SQL query:  select * from (SELECT CUSTOMER_NAME,COUNT(*) AS UNIT FROM CHATGPT_RESERVATION_MASTER WHERE (EXTRACT(YEAR FROM BOOKING_DATE) = EXTRACT(YEAR FROM SYSDATE) or EXTRACT(YEAR FROM RESERVE_DATE) = EXTRACT(YEAR FROM SYSDATE)) and status IN ('Booked','Reserved') GROUP BY CUSTOMER_NAME ORDER BY UNIT DESC) where ROWNUM =1

    Example 125 - customer contact details for booked units
    SQL query: SELECT mstr.PRE_RESERVE_NO,mstr.UNIT,mstr.CUSTOMER_NAME,cus.VALUE as contact FROM CHATGPT_RESERVATION_MASTER mstr,PN_RESERVE_CUSTOMER_DTL dtl ,AR_CUSTOMER_CONTACTS cus WHERE mstr.ID = dtl.RESERVATION_ID and dtl.IS_PRIMARY =1 and cus.IS_PRIMARY=1 and cus.CUSTOMER_ID=dtl.CUSTOMER_ID and mstr.status IN ('Booked','Reserved')  group by mstr.PRE_RESERVE_NO,mstr.UNIT,mstr.CUSTOMER_NAME,cus.VALUE

    Example 126 - Indian customer contacts
    SQL query: SELECT mstr.PRE_RESERVE_NO,mstr.UNIT,mstr.CUSTOMER_NAME,cus.VALUE as contact FROM CHATGPT_RESERVATION_MASTER mstr,PN_RESERVE_CUSTOMER_DTL dtl ,AR_CUSTOMER_CONTACTS cus WHERE mstr.ID = dtl.RESERVATION_ID and dtl.IS_PRIMARY =1 and cus.IS_PRIMARY=1 and cus.CUSTOMER_ID=dtl.CUSTOMER_ID and mstr.nationality = 'Indian'  group by mstr.PRE_RESERVE_NO,mstr.UNIT,mstr.CUSTOMER_NAME,cus.VALUE  

    Example 127 - Available bank accounts
    SQL query: SELECT bank.DDATE as ACCOUNT_CREATED_ON,bank.ACCOUNT_NAME,bank.CREATED_BY FROM CHATGPT_BANK_BALANCE_MASTER bank 

    Example 128 - Available bank balances
    SQL query: SELECT bank.DDATE as ACCOUNT_CREATED_ON,bank.AMOUNT,bank.ACCOUNT_NAME,bank.CREATED_BY FROM CHATGPT_BANK_BALANCE_MASTER bank 

    Example 129 - bank balance updated by jenvisha
    SQL query: SELECT bank.DDATE as ACCOUNT_CREATED_ON,bank.AMOUNT,bank.ACCOUNT_NAME,bank.CREATED_BY AS CREATED_BY FROM CHATGPT_BANK_BALANCE_MASTER bank where lower(CREATED_BY)=lower('Jenvisha')

    Example 130 - bank balance comparison for current month and last month
    SQL query: WITH LatestAmounts AS (SELECT bank.DDATE AS ACCOUNT_CREATED_ON, bank.AMOUNT, bank.ACCOUNT_NAME, bank.CREATED_BY, EXTRACT(MONTH FROM bank.DDATE) AS MONTH_NUM, EXTRACT(YEAR FROM bank.DDATE) AS YEAR_NUM, ROW_NUMBER() OVER (PARTITION BY EXTRACT(MONTH FROM bank.DDATE), EXTRACT(YEAR FROM bank.DDATE), bank.ACCOUNT_NAME ORDER BY bank.DDATE DESC) AS RN FROM CHATGPT_BANK_BALANCE_MASTER bank WHERE EXTRACT(YEAR FROM bank.DDATE) = EXTRACT(YEAR FROM SYSDATE) AND EXTRACT(MONTH FROM bank.DDATE) IN (EXTRACT(MONTH FROM SYSDATE), EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1)))) SELECT current_month.AMOUNT AS CURRENT_MONTH_AMOUNT, previous_month.AMOUNT AS PREVIOUS_MONTH_AMOUNT, current_month.AMOUNT - previous_month.AMOUNT AS DIFFERENCE, current_month.ACCOUNT_NAME FROM LatestAmounts current_month JOIN LatestAmounts previous_month ON current_month.ACCOUNT_NAME = previous_month.ACCOUNT_NAME AND current_month.MONTH_NUM = EXTRACT(MONTH FROM SYSDATE) AND previous_month.MONTH_NUM = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1)) WHERE current_month.RN = 1 AND previous_month.RN = 1

    Example 131 - account ES-HATIMI-MAIN-4512 bank balance comparison for current month and last month
    SQL query: WITH LatestAmounts AS (SELECT bank.DDATE AS ACCOUNT_CREATED_ON, bank.AMOUNT, bank.ACCOUNT_NAME, bank.CREATED_BY, EXTRACT(MONTH FROM bank.DDATE) AS MONTH_NUM, EXTRACT(YEAR FROM bank.DDATE) AS YEAR_NUM, ROW_NUMBER() OVER (PARTITION BY EXTRACT(MONTH FROM bank.DDATE), EXTRACT(YEAR FROM bank.DDATE), bank.ACCOUNT_NAME ORDER BY bank.DDATE DESC) AS RN FROM CHATGPT_BANK_BALANCE_MASTER bank WHERE EXTRACT(YEAR FROM bank.DDATE) = EXTRACT(YEAR FROM SYSDATE) AND EXTRACT(MONTH FROM bank.DDATE) IN (EXTRACT(MONTH FROM SYSDATE), EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1)))) SELECT current_month.AMOUNT AS CURRENT_MONTH_AMOUNT, previous_month.AMOUNT AS PREVIOUS_MONTH_AMOUNT, current_month.AMOUNT - previous_month.AMOUNT AS DIFFERENCE, current_month.ACCOUNT_NAME FROM LatestAmounts current_month JOIN LatestAmounts previous_month ON current_month.ACCOUNT_NAME = previous_month.ACCOUNT_NAME AND current_month.MONTH_NUM = EXTRACT(MONTH FROM SYSDATE) AND previous_month.MONTH_NUM = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1)) WHERE current_month.RN = 1 AND previous_month.RN = 1 and lower(previous_month.ACCOUNT_NAME) = lower('ES-HATIMI-MAIN-4512')

    Example 132 - bank balance comparison for this month and july month
    SQL query: WITH LatestAmounts AS (SELECT bank.DDATE AS ACCOUNT_CREATED_ON, bank.AMOUNT, bank.ACCOUNT_NAME, bank.CREATED_BY, EXTRACT(MONTH FROM bank.DDATE) AS MONTH_NUM, EXTRACT(YEAR FROM bank.DDATE) AS YEAR_NUM, ROW_NUMBER() OVER (PARTITION BY EXTRACT(MONTH FROM bank.DDATE), EXTRACT(YEAR FROM bank.DDATE), bank.ACCOUNT_NAME ORDER BY bank.DDATE DESC) AS RN FROM CHATGPT_BANK_BALANCE_MASTER bank WHERE EXTRACT(YEAR FROM bank.DDATE) = EXTRACT(YEAR FROM SYSDATE) AND EXTRACT(MONTH FROM bank.DDATE) IN (EXTRACT(MONTH FROM SYSDATE), 7)) SELECT current_month.AMOUNT AS CURRENT_MONTH_AMOUNT, july.AMOUNT AS JULY_AMOUNT, current_month.AMOUNT - july.AMOUNT AS DIFFERENCE, current_month.ACCOUNT_NAME FROM LatestAmounts current_month JOIN LatestAmounts july ON current_month.ACCOUNT_NAME = july.ACCOUNT_NAME AND current_month.MONTH_NUM = EXTRACT(MONTH FROM SYSDATE) AND july.MONTH_NUM = 7 WHERE current_month.RN = 1 AND july.RN = 1

    Example 133 - Units with undeposit cheques
    SQL query: select mstr.PRE_RESERVE_NO,mstr.RECEIPT_NO,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.RECEIPT_DATE,mstr.RECEIPT_AMOUNT,mstr.CHEQUE_NO,mstr.CHEQUE_DATE from CHATGPT_RESERVATION_MASTER mstr where mstr.CHEQUE_NO is not null 

    Example 134 - Cancelled undeposit cheques
    SQL query: select mstr.PRE_RESERVE_NO,mstr.RECEIPT_NO,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.RECEIPT_DATE,mstr.RECEIPT_AMOUNT,mstr.CHEQUE_NO,mstr.CHEQUE_DATE from CHATGPT_RESERVATION_MASTER mstr where mstr.CHEQUE_NO is not null AND IS_CHEQUE_CANCELLED='I' 

    Example 135 - undeposit cheques from last month
    SQL query: select mstr.PRE_RESERVE_NO,mstr.RECEIPT_NO,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.RECEIPT_DATE,mstr.RECEIPT_AMOUNT,mstr.CHEQUE_NO,mstr.CHEQUE_DATE from CHATGPT_RESERVATION_MASTER mstr where mstr.CHEQUE_NO is not null AND mstr.RECEIPT_DATE BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1)) 

    Example 136 - undeposit cheques from this month
    SQL query: select mstr.PRE_RESERVE_NO,mstr.RECEIPT_NO,mstr.BUILDING,mstr.BOOKING_DATE,mstr.RESERVE_DATE,mstr.UNIT,mstr.CUSTOMER_NAME,mstr.BROKER_NAME,mstr.AGENT_NAME,mstr.RECEIPT_DATE,mstr.RECEIPT_AMOUNT,mstr.CHEQUE_NO,mstr.CHEQUE_DATE from CHATGPT_RESERVATION_MASTER mstr where mstr.CHEQUE_NO is not null AND TRUNC(mstr.CHEQUE_DATE) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE) 

    Example 137 - Approval data for pre reserve no 1482
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.APPROVAL_TYPE, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, appr.COMMENTS, (SELECT login_name FROM fnd_user_info WHERE user_info_id = appr.APPROVER_USER_ID) AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr WHERE appr.RESERVATION_ID = (SELECT id FROM CHATGPT_RESERVATION_MASTER WHERE PRE_RESERVE_NO=1482) AND appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Example 138 - Units Pending with Joclaire Approval
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, usinfo.login_name AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr, fnd_user_info usinfo WHERE LOWER(usinfo.login_name) = LOWER('joclaire') AND appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID AND usinfo.user_info_id = appr.APPROVER_USER_ID AND appr.APPROVAL_FLAG = 'P' ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Example 139 - units Approved by Jawhara
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, usinfo.login_name AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr, fnd_user_info usinfo WHERE LOWER(usinfo.login_name) = LOWER('Jawhara') AND appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID AND usinfo.user_info_id = appr.APPROVER_USER_ID AND appr.APPROVAL_FLAG = 'A' ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Example 140 - approvals sent to jcolaire this week
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, usinfo.login_name AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr, fnd_user_info usinfo WHERE LOWER(usinfo.login_name) = LOWER('Jawhara') AND appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID AND usinfo.user_info_id = appr.APPROVER_USER_ID AND RECEIVED_DATE BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 7 ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Exaple 141 - units pending for approval
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, usinfo.login_name AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr, fnd_user_info usinfo WHERE appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID AND usinfo.user_info_id = appr.APPROVER_USER_ID AND appr.APPROVAL_FLAG = 'P' ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Exaple 142 - approval details for unit MGT1-FL34-3404
    SQL query: SELECT mstr.PRE_RESERVE_NO, appr.RECEIVED_DATE AS SUBMITTED_DT, appr.APPROVED_DATE AS ACTION_DT, usinfo.login_name AS APPROVER_NAME, CASE WHEN appr.APPROVAL_FLAG = 'P' THEN 'PENDING' WHEN appr.APPROVAL_FLAG = 'I' THEN 'IN PROGRESS' WHEN appr.APPROVAL_FLAG = 'A' THEN 'APPROVED' WHEN appr.APPROVAL_FLAG = 'R' THEN 'REJECTED' END AS STATUS, mstr.UNIT, mstr.CUSTOMER_NAME FROM FND_PROP_RESERVE_APPROVAL appr, CHATGPT_RESERVATION_MASTER mstr, fnd_user_info usinfo WHERE appr.IS_ACTIVE=1 AND appr.IS_DELETED=0 AND appr.RESERVATION_ID = mstr.ID AND usinfo.user_info_id = appr.APPROVER_USER_ID AND mstr.UNIT = 'MGT1-FL34-3404' ORDER BY appr.APPROVAL_TYPE DESC, appr.LEVEL_NO

    Example 143 - title deed for unit MGT1-FL38-3805
    SQL query: SELECT deed.TITLE_DEED, deed.REG_DATE, deed.IS_TRANSFER, mstr.BUILDING, mstr.BOOKING_DATE, mstr.RESERVE_DATE, mstr.UNIT, mstr.CUSTOMER_NAME FROM CHATGPT_RESERVATION_MASTER mstr, (SELECT ID, TITLE_DEED, REG_DATE, DESCRIPTION, UNIT_ID, RESERVATION_ID, ORG_ID, IS_ACTIVE, IS_TRANSFER, CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = PN_RESERVE_TITLE_DEED_REGIS.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS WHERE IS_ACTIVE = 1 AND IS_DELETED = 0 UNION ALL SELECT deed.ID, deed.TITLE_DEED, deed.REG_DATE, deed.DESCRIPTION, deed.UNIT_ID, thdr.NEW_RESERVATION_ID AS RESERVATION_ID, deed.ORG_ID, deed.IS_ACTIVE, deed.IS_TRANSFER, deed.CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = deed.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS deed, PN_TRANSFER_HDR thdr WHERE deed.RESERVATION_ID = thdr.RESERVATION_ID AND deed.IS_ACTIVE = 1 AND deed.IS_DELETED = 0 AND deed.IS_TRANSFER = 1) deed WHERE mstr.ID = deed.RESERVATION_ID AND deed.TITLE_DEED IS NOT NULL AND mstr.UNIT = 'MGT1-FL38-3805'

    Example 144 - title deeds registered in last month 
    SQL query: SELECT deed.TITLE_DEED, deed.REG_DATE, deed.IS_TRANSFER, mstr.BUILDING, mstr.BOOKING_DATE, mstr.RESERVE_DATE, mstr.UNIT, mstr.CUSTOMER_NAME FROM CHATGPT_RESERVATION_MASTER mstr, (SELECT ID, TITLE_DEED, REG_DATE, DESCRIPTION, UNIT_ID, RESERVATION_ID, ORG_ID, IS_ACTIVE, IS_TRANSFER, CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = PN_RESERVE_TITLE_DEED_REGIS.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS WHERE IS_ACTIVE = 1 AND IS_DELETED = 0 UNION ALL SELECT deed.ID, deed.TITLE_DEED, deed.REG_DATE, deed.DESCRIPTION, deed.UNIT_ID, thdr.NEW_RESERVATION_ID AS RESERVATION_ID, deed.ORG_ID, deed.IS_ACTIVE, deed.IS_TRANSFER, deed.CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = deed.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS deed, PN_TRANSFER_HDR thdr WHERE deed.RESERVATION_ID = thdr.RESERVATION_ID AND deed.IS_ACTIVE = 1 AND deed.IS_DELETED = 0 AND deed.IS_TRANSFER = 1) deed WHERE mstr.ID = deed.RESERVATION_ID AND deed.TITLE_DEED IS NOT NULL AND TRUNC(deed.REG_DATE) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE)

    Example 145 - title deeds registered in this week
    SQL query: SELECT deed.TITLE_DEED, deed.REG_DATE, deed.IS_TRANSFER, mstr.BUILDING, mstr.BOOKING_DATE, mstr.RESERVE_DATE, mstr.UNIT, mstr.CUSTOMER_NAME FROM CHATGPT_RESERVATION_MASTER mstr, (SELECT ID, TITLE_DEED, REG_DATE, DESCRIPTION, UNIT_ID, RESERVATION_ID, ORG_ID, IS_ACTIVE, IS_TRANSFER, CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = PN_RESERVE_TITLE_DEED_REGIS.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS WHERE IS_ACTIVE = 1 AND IS_DELETED = 0 UNION ALL SELECT deed.ID, deed.TITLE_DEED, deed.REG_DATE, deed.DESCRIPTION, deed.UNIT_ID, thdr.NEW_RESERVATION_ID AS RESERVATION_ID, deed.ORG_ID, deed.IS_ACTIVE, deed.IS_TRANSFER, deed.CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = deed.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS deed, PN_TRANSFER_HDR thdr WHERE deed.RESERVATION_ID = thdr.RESERVATION_ID AND deed.IS_ACTIVE = 1 AND deed.IS_DELETED = 0 AND deed.IS_TRANSFER = 1) deed WHERE mstr.ID = deed.RESERVATION_ID AND deed.TITLE_DEED IS NOT NULL AND deed.REG_DATE BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 7

    Example 146 - transfered title deeds 
    SQL query: SELECT deed.TITLE_DEED, deed.REG_DATE,mstr.BUILDING, mstr.BOOKING_DATE, mstr.RESERVE_DATE, mstr.UNIT, mstr.CUSTOMER_NAME FROM CHATGPT_RESERVATION_MASTER mstr, (SELECT ID, TITLE_DEED, REG_DATE, DESCRIPTION, UNIT_ID, RESERVATION_ID, ORG_ID, IS_ACTIVE, IS_TRANSFER, CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = PN_RESERVE_TITLE_DEED_REGIS.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS WHERE IS_ACTIVE = 1 AND IS_DELETED = 0 UNION ALL SELECT deed.ID, deed.TITLE_DEED, deed.REG_DATE, deed.DESCRIPTION, deed.UNIT_ID, thdr.NEW_RESERVATION_ID AS RESERVATION_ID, deed.ORG_ID, deed.IS_ACTIVE, deed.IS_TRANSFER, deed.CREATED_ON, (SELECT LOGIN_NAME FROM FND_USER_INFO WHERE USER_INFO_ID = deed.CREATED_BY) CREATED_BY FROM PN_RESERVE_TITLE_DEED_REGIS deed, PN_TRANSFER_HDR thdr WHERE deed.RESERVATION_ID = thdr.RESERVATION_ID AND deed.IS_ACTIVE = 1 AND deed.IS_DELETED = 0 AND deed.IS_TRANSFER = 1) deed WHERE mstr.ID = deed.RESERVATION_ID AND deed.TITLE_DEED IS NOT NULL AND deed.IS_TRANSFER = 1

    Example 3 - Units Sold on Today
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') AND TRUNC(booking_date) = TO_DATE(SYSDATE, 'DD-MM-YY')
    # SQL query: SELECT building, unit_code, customer_name FROM chatgpt_sale_master WHERE unit_status IN ('Booked','Reserved') AND TRUNC(booking_date) = TO_DATE(SYSDATE, 'DD-MM-YY')

    Example 4 - Units Sold from Building 'MGTL'
    SQL query: select BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME from CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') AND upper(building)=upper('MGTL')

    Example 6 - All units Sold by broker PHIRDOS STAR PROPERTY
    SQL query: SELECT BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME,BROKER_NAME,AGENT_NAME FROM CHATGPT_RESERVATION_MASTER WHERE status IN ('Booked','Reserved') AND LOWER(broker_name) LIKE '%phirdos star property%'

    Example 7 - How many customers purchased 1 bedroom?
    SQL query: SELECT BUILDING,BOOKING_DATE,RESERVE_DATE,UNIT,CUSTOMER_NAME,nationality FROM CHATGPT_RESERVATION_MASTER where unit_specs_name = '1 BHK' and status IN ('Booked','Reserved')
    # SQL query: SELECT q.building, q.unit_code, q.booking_date, q.customer_name, q.nationality FROM chatgpt_sale_master q LEFT JOIN chatgpt_unit_master a ON a.unit_code = q.unit_code WHERE q.unit_status IN ('Booked','Reserved') AND a.unit_specs_name = '1 BHK'

    Example 8 - Total sale value of the MGTL
    SQL query: SELECT SUM(Sale_value) FROM CHATGPT_RESERVATION_MASTER where status IN ('Booked','Reserved') AND upper(building)=upper('MGTL')
    # SQL query: SELECT SUM(Sale_value) FROM chatgpt_sale_master WHERE unit_status IN ('Booked','Reserved') AND building = 'TOWER A'

    Example 9 - Sale value for Today's pre-reserved units
    SQL query: SELECT SUM(Sale_value) FROM CHATGPT_RESERVATION_MASTER WHERE status IN ('Pre-Reserved') AND TRUNC(PRE_RESERVE_DATE) = TRUNC(SYSDATE)
    # SQL query: SELECT SUM(Sale_value) FROM chatgpt_pre_reserved WHERE unit_status IN ('Pre-Reserved') AND TRUNC(block_date) = TRUNC(SYSDATE)

    Example 10 - Last month's total sale value
    SQL query: SELECT SUM(Sale_value) last_month_salevalue FROM CHATGPT_RESERVATION_MASTER WHERE status IN ('Booked','Reserved') AND booking_date BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))
    # SQL query: SELECT SUM(Sale_value) last_month_salevalue FROM chatgpt_sale_master WHERE unit_status IN ('Booked','Reserved') AND booking_date BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))

    Example 11 - Last month's average sale value
    SQL query: SELECT SUM(Sale_value) / ROUND(LAST_DAY(ADD_MONTHS(SYSDATE, -1)) - TO_DATE('01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY'), 'DD-MON-YYYY')) average_sale_value FROM CHATGPT_RESERVATION_MASTER WHERE status IN ('Booked','Reserved') AND booking_date BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))
    # SQL query: SELECT SUM(Sale_value) / ROUND(LAST_DAY(ADD_MONTHS(SYSDATE, -1)) - TO_DATE('01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY'), 'DD-MON-YYYY')) average_sale_value FROM chatgpt_sale_master WHERE unit_status IN ('Booked','Reserved') AND booking_date BETWEEN '01-' || TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'MON-YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))

    Example 12 - Top 5 agents who sold the units in the last 10 days
    SQL query: SELECT * FROM (SELECT agent_name, COUNT(*) FROM chatgpt_sale_master WHERE agent_name IS NOT NULL AND unit_status IN ('Booked','Reserved') AND BLOCK_DATE BETWEEN SYSDATE - 10 AND SYSDATE GROUP BY agent_name ORDER BY COUNT(*) DESC) WHERE ROWNUM <= 5

    Example 13 - Name, unit code, agent, broker for customer ID 753
    SQL query: SELECT customer_name, unit_code, agent_name, broker_name, sale_value FROM chatgpt_sale_master WHERE customer_id = 753

    Example 14 - Multiple brokers with the same agent
    SQL query: SELECT broker_name, agent_name FROM chatgpt_sale_master WHERE broker_name IS NOT NULL AND agent_name IN (SELECT agent_name FROM (SELECT agent_name, COUNT(*) FROM (SELECT agent_name, broker_name FROM chatgpt_sale_master WHERE broker_name IS NOT NULL GROUP BY agent_name, broker_name) GROUP BY agent_name HAVING COUNT(*) > 1)) GROUP BY agent_name, broker_name ORDER BY agent_name

    Example 15 - Customers who bought more than 5 units
    SQL query: SELECT * FROM (SELECT customer_name, COUNT(*) FROM chatgpt_sale_master WHERE unit_status IN ('Booked','Reserved') GROUP BY customer_name ORDER BY COUNT(*) DESC) WHERE ROWNUM <= 5

    Example 16 - Tell us all organization list
    SQL query: SELECT customer_name FROM chatgpt_customer_master WHERE ctype = 'ORG'

    Example 17 - View customers whose passports expired and are from India
    SQL query: SELECT customer_name FROM chatgpt_customer_master WHERE nationality LIKE '%India%' AND passport_expiry_date < TRUNC(SYSDATE)

    Example 18 - When did management sign for the unit?
    SQL query: SELECT mgmt_sign_date FROM chatgpt_pra WHERE unit_code = 'MG1-FL1-101'

    Example 19 - How many units were management signed in the last 10 days?
    SQL query: SELECT COUNT(*) FROM chatgpt_pra WHERE mgmt_sign_date IS NOT NULL AND mgmt_sign_date BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE)

    Example 20 - How many units are pending for client sign?
    SQL query: SELECT COUNT(*) FROM chatgpt_pra WHERE client_sign_date IS NULL

    Example 21 - Top 5 Indian customers who need to pay the most
    SQL query: SELECT * FROM (SELECT x.customer_name, SUM(x.inv_balance) FROM chatgpt_customer_bal x LEFT JOIN chatgpt_customer_master y ON y.customer_id = x.customer_id WHERE y.nationality LIKE '%India%' AND x.doc_type IN ('ERES', 'ERES Difference', 'ERES Difference 1', 'Home Automation', 'INSTALLMENT') GROUP BY x.customer_name HAVING SUM(x.inv_balance) > 0 ORDER BY SUM(inv_balance) DESC) WHERE ROWNUM <= 5

    Example 22 - Month-wise top agent for the last 6 months
    SQL query: SELECT * FROM (SELECT agent_name, TO_CHAR(booking_date, 'MON-YYYY') AS month, COUNT(*) AS sold FROM chatgpt_sale_master WHERE agent_name IS NOT NULL AND unit_status IN ('Booked', 'Reserved') GROUP BY agent_name, TO_CHAR(booking_date, 'MON-YYYY')) x WHERE x.month || x.sold IN (SELECT month || sold FROM (SELECT MAX(sold) AS sold, month FROM (SELECT agent_name, TO_CHAR(booking_date, 'MON-YYYY') AS month, COUNT(*) AS sold FROM chatgpt_sale_master WHERE agent_name IS NOT NULL AND unit_status IN ('Booked', 'Reserved') GROUP BY agent_name, TO_CHAR(booking_date, 'MON-YYYY') ORDER BY COUNT(*) DESC) GROUP BY month))

    Example 23 - Tell me the details for offer no 430
    SQL query: SELECT x.customer_name, x.unit_code, y.agent_name, y.broker_name, y.sale_value FROM chatgpt_pra x LEFT JOIN chatgpt_sale_master y ON y.unit_code = x.unit_code WHERE x.offer_no = 430

    Example 24 - What is the narration for receipt no 46
    SQL query: SELECT narration FROM chatgpt_receipt_dtl2 WHERE receipt_no = 46

    Example 25 - Get narration by receipt no 46
    SQL query: SELECT narration FROM chatgpt_receipt_dtl2 WHERE receipt_no = 46

    Example 26 - Is this receipt a security deposit by receipt no?
    SQL query: SELECT COUNT(*) FROM chatgpt_receipt_dtl2 WHERE receipt_no = 46 AND sec_depo_receipt = 'Yes'

    Example 27 - What is the security deposit for customer Vishal anand as unit MGT1-FL15-1504?
    SQL query: SELECT SUM(amount) FROM chatgpt_receipt_dtl2 WHERE lower(customer) = lower('Vishal anand') AND sec_depo_receipt = 'Yes' and unit_code = 'MGT1-FL15-1504'

    Example 28 - All details of receipt no 3747
    SQL query: SELECT a.RECEIPT_NO, a.RECEIPT_DATE, a.cheque_no, a.cheque_date, a.CUSTOMER_ID, a.NARRATION, a.RECEIVED_FROM, c.offer_no, a.sec_depo_receipt, a.mode_of_pay, a.unit_id, a.unit_code, b.building, b.unit_specs_name, c.customer_name, c.sale_value, c.broker_name, c.agent_name FROM chatgpt_receipt_dtl2 a LEFT JOIN chatgpt_unit_master b ON b.unit_id = a.unit_id LEFT JOIN chatgpt_sale_master c ON c.unit_code = b.unit_code AND a.customer_id = c.customer_id WHERE receipt_no = 3747

    Example 29 - What is the total receipt amount of Unit MGT1-FL25-2506?
    SQL query: SELECT SUM(a.amount) FROM chatgpt_receipt_dtl2 a WHERE a.unit_code = 'MGT1-FL25-2506'

    Example 30 - Show all the receipts/collection for the Unit
    SQL query: SELECT a.RECEIPT_NO, a.RECEIPT_DATE, a.cheque_no, a.cheque_date, a.CUSTOMER_ID, a.NARRATION, a.RECEIVED_FROM, c.offer_no, a.sec_depo_receipt, a.mode_of_pay, b.unit_code, b.building, b.unit_specs_name, c.customer_name, c.sale_value, c.broker_name, c.agent_name FROM chatgpt_receipt_dtl2 a LEFT JOIN chatgpt_unit_master b ON b.unit_id = a.unit_id LEFT JOIN chatgpt_sale_master c ON c.unit_code = b.unit_code AND a.customer_id = c.customer_id WHERE c.unit_code = 'MGT1-FL25-2506'

    Example 31 - What is the total receipt/collection amount of Customer?
    SQL query: SELECT SUM(a.amount) FROM chatgpt_receipt_dtl2 a LEFT JOIN chatgpt_unit_master b ON b.unit_id = a.unit_id LEFT JOIN chatgpt_sale_master c ON c.unit_code = b.unit_code AND a.customer_id = c.customer_id WHERE c.customer_name = 'FRIEDRICH TESMANN'

    Example 32 - Show all the receipts/collection for the Customer
    SQL query: SELECT a.RECEIPT_NO, a.RECEIPT_DATE, a.cheque_no, a.cheque_date, a.CUSTOMER_ID, a.NARRATION, a.RECEIVED_FROM, c.offer_no, a.sec_depo_receipt, a.mode_of_pay, a.unit_code, b.building, b.unit_specs_name, c.customer_name, c.sale_value, c.broker_name, c.agent_name FROM chatgpt_receipt_dtl2 a LEFT JOIN chatgpt_unit_master b ON b.unit_id = a.unit_id LEFT JOIN chatgpt_sale_master c ON c.unit_code = b.unit_code AND a.customer_id = c.customer_id WHERE c.customer_name = 'FRIEDRICH TESMANN'

    Example 33 - How much collected today for Tower A?
    SQL query: SELECT COUNT(*) FROM chatgpt_receipt_dtl2 WHERE lower(building) = lower('TOWER A') AND TRUNC(receipt_date) = TRUNC(SYSDATE)

    Example 34 - How many receipts/collection came today for Tower A with mode by link?
    SQL query: SELECT COUNT(*) FROM chatgpt_receipt_dtl2 WHERE TRUNC(receipt_date) = TRUNC(SYSDATE) AND mode_of_pay = 'BY LINK' and lower(building) = lower('TOWER A')

    Example 35 - Give me the count of customers and their nationality who purchased room studio in Tower A
    SQL query: SELECT COUNT(*), x.nationality FROM chatgpt_sale_master x LEFT JOIN chatgpt_unit_master z ON z.unit_code = x.unit_code WHERE z.unit_specs_name = 'STUDIO' AND x.building = 'TOWER A' GROUP BY x.nationality

    Example 36 - List all notes details for the Unit
    SQL query: SELECT note, offer_no, created_on, login_name FROM chatgpt_notes WHERE offer_no IN (SELECT offer_no FROM chatgpt_sale_master WHERE unit_code = 'MGT2-FL24-2407') ORDER BY created_on DESC

    Example 37 - List all payment plans for the Unit
    SQL query: SELECT * FROM chatgpt_payment_plan WHERE offer_no IN (SELECT offer_no FROM chatgpt_sale_master WHERE unit_code = 'MGT2-FL24-2407')

    Example 38 - Give me the total amount by month-wise with total count
    SQL query: SELECT TO_CHAR(due_date, 'YYYY-MON'), SUM(amount), COUNT(offer_no) FROM chatgpt_payment_plan GROUP BY TO_CHAR(due_date, 'YYYY-MON')

    Example 39 - What is the payment plan for 3805 Tower A?
    SQL query: SELECT * FROM chatgpt_payment_plan WHERE offer_no IN (SELECT offer_no FROM chatgpt_sale_master WHERE unit_code LIKE '%3805%' AND building = 'TOWER A')

    Example 40 - Give me details of sale value and total unit count by month-wise of unit specs studio sold
    SQL query: SELECT TO_CHAR(booking_date, 'YYYY-MON'), SUM(x.sale_value), COUNT(x.unit_code) FROM chatgpt_sale_master x LEFT JOIN chatgpt_unit_master z ON z.unit_code = x.unit_code WHERE z.unit_specs_name = 'STUDIO' GROUP BY TO_CHAR(booking_date, 'YYYY-MON')

    Example 41 - Give me the packages of operating unit 'HATIMI' and building 'HATIMI RESIDENCES TOWER B'? 
    SQL query: select ORG_NAME,BUILDING,LOCATION_NAME,PACKAGE_NAME from chatgpt_hm_package_hdr where upper(org_name) = upper('HATIMI') and upper(building)=upper('HATIMI RESIDENCES TOWER B')

    Example 42 - Give me the details of package '2BHK-PREMIUM PLATINUM FURNITURE PACKAGE' under operating unit 'FPDL-MGMT_UNITS' and building 'MG2_MU' and location 'Jumeirah Village Circle_MU' and unit type = 'TYPE A'?
    SQL query: SELECT AMENITIES_TYPE,QTY,PRICE,DESCRIPTION,TYPE FROM CHATGPT_HM_PACKAGE_DTL dtl,CHATGPT_HM_PACKAGE_HDR hdr 
              where dtl.HDR_ID = hdr.HDR_ID AND hdr.ORG_NAME ='FPDL-MGMT_UNITS' AND hdr.BUILDING='MG2_MU' AND hdr.LOCATION_NAME = 'Jumeirah Village Circle_MU' AND hdr.UNIT_TYPE = 'TYPE A' AND hdr.PACKAGE_NAME='2BHK-PREMIUM PLATINUM FURNITURE PACKAGE'

    Example 43 - payment plan HRA-MAY-2024 units? 
    SQL query: SELECT unit_code FROM chatgpt_sale_master WHERE offer_no IN (SELECT DISTINCT offer_no FROM chatgpt_payment_plan WHERE UPPER(PLAN_NAME) = UPPER('HRA-MAY-2024'))


    # Example 43 - Booked units
    # SELECT u.UNIT_CODE,r.RESERVE_DATE FROM PN_RESERVATION_HDR r
    # JOIN PN_UNITS u ON r.UNIT_ID = u.UNIT_ID
    # JOIN PN_SALES_STATUS s ON r.STATUS = s.STATUS_ID
    # WHERE s.STATUS = 'Booked' and r.IS_ACTIVE=1 and r.IS_DELETED=0

    # Example 44 - customer names for booked units in last month?
    #   SELECT
    #       c."NAME"
    #   FROM
    #       PN_RESERVATION_HDR r
    #   JOIN
    #       PN_UNITS u
    #   ON
    #       r.UNIT_ID = u.UNIT_ID
    #   JOIN
    #       PN_SALES_STATUS s
    #   ON
    #       r.STATUS = s.STATUS_ID
    #   JOIN
    #       PN_RESERVE_CUSTOMER_DTL d
    #   ON
    #       r.ID = d.RESERVATION_ID
    #   JOIN
    #       AR_CUSTOMER c
    #   ON
    #       d.CUSTOMER_ID = c.CUSTOMER_ID
    #   WHERE
    #       s.STATUS = 'Booked' AND TO_CHAR(r.RESERVE_DATE, 'MM-YY') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, -1), 'MM-YY') and r.IS_ACTIVE=1 and r.IS_DELETED=0

    Example 44 - list agents?
    SELECT LOGIN_NAME FROM FND_USER_INFO UI LEFT JOIN PN_AGENTS AG ON UI.USER_INFO_ID=AG.USER_ID WHERE AG.IS_ACTIVE=1 AND AG.IS_DELETED=0 
    
    Example 45 - home automation Package name for building is HATIMI RESIDENCES TOWER B, location is DUBAI ISLAND, org is HATIMI
    select BUILDING,LOCATION_NAME,UNIT_TYPE,PACKAGE_NAME,ORG_NAME from CHATGPT_HM_PACKAGE_HDR where IS_ACTIVE=1 and ORG_NAME ='HATIMI' AND BUILDING='HATIMI RESIDENCES TOWER B' AND LOCATION_NAME='DUBAI ISLAND'

    Example 46 - give the quantity of SMART BED ROOM LOCK from building is HATIMI RESIDENCES TOWER B, location is DUBAI ISLAND, org is HATIMI,package is 1 BHK TYPE 2 (FIRST FLOOR)
    select QTY from CHATGPT_HM_PACKAGE_DTL where DESCRIPTION='SMART BED ROOM LOCK' and hdr_id = (select HDR_ID from CHATGPT_HM_PACKAGE_HDR where ORG_NAME ='HATIMI' AND BUILDING='HATIMI RESIDENCES TOWER B' AND LOCATION_NAME='DUBAI ISLAND' and PACKAGE_NAME ='1 BHK TYPE 2 (FIRST FLOOR)' )

    Example 47 - give released units
    SELECT UNIT_CODE,UNIT_NAME FROM CHATGPT_RELEASED_NOTRELEASED WHERE IS_RELEASED = 'RELEASED'

    Example 48 - give the lists of all visa?
    SELECT COUNTRY_NAME,UID_NO,PROFESSION,SPONSOR,EXPIRTY_DATE,REMARKS,ISSUE_DATE FROM CHATGPT_VISA

    Example 49 - what is country name for passport owner Batul Mustafa Fakhruddin?
    SELECT COUNTRY_NAME from CHATGPT_PASSPORT where NAME = 'Batul Mustafa Fakhruddin'

    Example 50 - emirates id OR eid details for Abbas Akbar Ali Fakhruddin?
    SELECT * FROM CHATGPT_EID WHERE NAME = 'Abbas Akbar Ali Fakhruddin'

    Example 51 - list rework status tickets
    SELECT * from CHATGPT_TICKETS where status = 'REWORK'   

    Example 52 - pra details for cusotmer ALA BARAC against unit 'MGT2-FL32-3201'?
    SELECT * FROM CHATGPT_PRA WHERE CUSTOMER_NAME='ALA BARAC' AND UNIT_CODE = 'MGT2-FL32-3201'

    Example 53 - spa details for cusotmer ALA BARAC against unit 'MGT2-FL32-3201'?
    SELECT * FROM CHATGPT_SPA WHERE CUSTOMER_NAME='ALA BARAC' AND UNIT_CODE = 'MGT2-FL32-3201'

    Example 54 - from sold unsold what is the due amount for customer Vladimir Bogatyr?
    SELECT * FROM CHATGPT_SOLD_UNSOLD WHERE CUSTOMER_NAME='Vladimir Bogatyr' 

    Example 55 - what is the amount for order id 201 from oqood registration?
    SELECT AMOUNT FROM CHATGPT_OQOOD WHERE ORDER_ID = 201

    Example 56 - In late payment What is the total invoice amount for customer AHMED MUSALLAM   NASER ALFANNAH ALJNEIBI?
    SELECT SUM(INVOICE_AMOUNT) FROM CHATGPT_LATEPAYMENT_FEE WHERE CUSTOMER_NAME = 'AHMED MUSALLAM   NASER ALFANNAH ALJNEIBI'

    Example 57 - shabbir approved late payments?
    SELECT * FROM CHATGPT_LATEPAYMENT_FEE WHERE UPPER(APPROVER_USER_ID) = UPPER('shabbir')

    Example 58 - Narrations for unit MGT1-FL5-506 in pdc?
    SELECT NARRATION FROM CHATGPT_PDC WHERE UNIT_CODE = 'MGT1-FL5-506'

    Example 59 - current month registered sales title deeds?
    SELECT * FROM CHATGPT_SALES_TITLEDEED WHERE TRUNC(REG_DATE) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE)

    Example 60 - what is security deposit amount for cutomer Sharfaraz Nawaz Musa with receipt no 6853
    SELECT amount FROM CHATGPT_SECURITY_DEPOSIT WHERE UPPER(CUSTOMER) = UPPER('Sharfaraz Nawaz Musa') AND RECEIPT_NO = 6853

    Example 61 - security deposits by indians
    SELECT * FROM CHATGPT_SECURITY_DEPOSIT WHERE UPPER(NATIONALITY) = UPPER('indian') 

    Example 62 - Unit cancellation details for cutomer Sayyad Raja with unit MGT1-FL36-3607
    SELECT * FROM CHATGPT_UNIT_CANCELLATION WHERE UPPER(CUSTOMER_NAME) = UPPER('Sayyad Raja') AND UNIT_CODE = 'MGT1-FL36-3607'

    Example 63 - list the cancelled units from org HATIMI
    SELECT * FROM CHATGPT_UNIT_CANCELLATION WHERE UPPER(ORG_NAME) = UPPER('HATIMI')

     Example 64 - Unit transfer details for MICHAEL MAYOROV  with unit MGT1-FL22-2208
    SELECT * FROM CHATGPT_UNIT_TRANSFER WHERE UPPER(CUSTOMER_NAME) = UPPER('MICHAEL MAYOROV ') AND UNIT_CODE = 'MGT1-FL22-2208'

    Example 65 - list the tranferred units from org FAKHRUDDIN PROPERTIES DEVELOPMENT LIMITED
    SELECT * FROM CHATGPT_UNIT_TRANSFER WHERE UPPER(ORG_NAME) = UPPER('FAKHRUDDIN PROPERTIES DEVELOPMENT LIMITED')

    Example 66 - list 14% bucket datas/units?
    SELECT * FROM CHATGPT_14PERCENT_BUCKET

    Example 67 - in 14% bucket is 48 hour notification sent for pre reservation no 1134?
    SELECT FOURTYEIGHT_HRS_NOTICE FROM CHATGPT_14PERCENT_BUCKET WHERE PRE_RESERVE_NO = 1134

    Example 68 - Reserved units from 14% bucket 
    SELECT UNIT_NAME FROM CHATGPT_14PERCENT_BUCKET WHERE UPPER(STATUS) = UPPER('Reserved')

    Example 69 - list installment bucket datas/units?
    SELECT * FROM CHATGPT_INSTALLMENT_BUCK

    Example 70 - in Installment bucket is Reminder sent for pre reservation no 431?
    SELECT REMINDER13 FROM CHATGPT_INSTALLMENT_BUCK WHERE PRE_RESERVE_NO = 431 and ROWNUM = 1

    Example 71 - Booked units from installment bucket 2nd due
    SELECT DISTINCT UNIT_CODE FROM CHATGPT_INSTALLMENT_BUCK WHERE UPPER(STATUS) = UPPER('Booked')

    Example 72 - list installment bucket 2nd due datas/units?
    SELECT * FROM CHATGPT_INSTALLMENT_BUCK_2DUE

    Example 73 - in Installment bucket 2nd due is Reminder sent for pre reservation no 431?
    SELECT REMINDER FROM CHATGPT_INSTALLMENT_BUCK_2DUE WHERE PRE_RESERVE_NO = 431 and ROWNUM = 1

    Example 74 - Booked units from installment bucket 2nd due
    SELECT DISTINCT UNIT_CODE FROM CHATGPT_INSTALLMENT_BUCK_2DUE WHERE UPPER(STATUS) = UPPER('Booked')

    Example 75 - Approval path for Auto Cancellatiion
    SELECT * FROM CHATGPT_APPROVAL_PATH WHERE UPPER(APPROVAL_PATH_NAME) = UPPER('Auto Cancellatiion') 

    Example 76 - who is the owner of property/building?
    SELECT OWNER FROM CHATGPT_BUILDING_MASTER WHERE UPPER(PROPERTY_NAME) = UPPER('HATIMI RESIDENCES TOWER A') 

    Example 77 - what is the purchase amount of Property/building Nathani Heights with property code Flat 6001?
    SELECT PURCHASE_AMOUNT FROM CHATGPT_BUILDING_MASTER WHERE UPPER(ltrim(rtrim(PROPERTY_NAME))) = UPPER('Nathani Heights') and UPPER(PROPERTY_CODE) = UPPER('Flat 6001')
    
    Example 78 - other charges for SOLDUNIT BOOKING
    SELECT * FROM CHATGPT_OTHER_CHARGES WHERE UPPER(OTHER_CHARGE_NAME) = UPPER('SOLDUNIT BOOKING') 

    Example 79 - Get floors from building hrb
    SELECT * FROM CHATGPT_FLOOR_MASTER WHERE UPPER(BUILDING) = UPPER('hrb') 

    Example 80 - Get Unit types from building hrb
    SELECT * FROM CHATGPT_UNIT_TYPE_MASTER WHERE UPPER(BUILDING) = UPPER('hrb') 

    Example 81 - Get Unit views from building hrb
    SELECT * FROM CHATGPT_UNIT_VIEW_MASTER WHERE UPPER(BUILDING) = UPPER('hrb') 
    

    Example 82 - Get Unit descriptions from building hrb
    SELECT * FROM CHATGPT_UNIT_DESC_MASTER WHERE UPPER(BUILDING) = UPPER('hrb') 
    
    Sql Condition have string means use the format:
      SELECT COLUMN1,COLUMN2 TABLE_NAME WHERE UPPER(COLUMN1) = UPPER('string')


    When asked to get the most recent record, use the format:
    SELECT *
    FROM TABLE
    WHERE Primarykey = (SELECT MAX(Primarykey) FROM TABLE)

    If a user related question involves country, you may need to join `FND_USER_INFO` and `FND_COUNTRY` using `COUNTRY_ID`.
    

    The `RESERVATION_ID` column in `PN_RESERVE_CUSTOMER_DTL` is a foreign key referencing the `ID` column in `PN_RESERVATION_HDR`.
    The `CUSTOMER_ID` column in `PN_RESERVE_CUSTOMER_DTL` is a foreign key referencing the `CUSTOMER_ID` column in `AR_CUSTOMER`.
    The `UNIT_ID` column in `PN_RESERVATION_HDR` is a foreign key referencing the `UNIT_ID` column in `PN_UNITS`.
    The `USER_ID` column in `PN_AGENTS` is a foreign key referencing the `USER_INFO_ID` column in `FND_USER_INFO`.

    Ensure all string conditions are case-insensitive.

    All the Date columns formats should be DD-MMM-YY.
    
    Also the ORACLE SQL command should not have ``` in beginning or end and and should be in ORACLE SQL query format.
    """


]

def handle_template1_query(question):
    try:
        response = get_gemini_response(question, prompt)
        rows = read_sql_query(response)
        if rows == 'DB_ERROR':
            return [["Please Try Again"], []]
        else:
            sentences = convert_rows_to_sentences(rows[1], question)
            return [sentences, rows[0]]
    except Exception as e:
        print(f"An error occurred: {e}")
        return [["Please Try Again"], []]  # or you can choose to return a different default value or raise the error again

